# 指定服务器端口
server:
  port: 8080

# 连接mysql数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/github?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root


# Mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lj.model

# 控制台打印sql语句
logging:
  level:
    com.lj.dao: debug  #com.lj.dao 是你项目中的dao层路径

